server {
    listen 80;
    server_name gamelygame.com www.gamelygame.com;

    return 301 https://gamelygame.com$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name www.gamelygame.com;

    ssl_certificate /etc/ssl/gamelygame/cert.pem;
    ssl_certificate_key /etc/ssl/gamelygame/key.pem;

    return 301 https://gamelygame.com$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name gamelygame.com;

    ssl_certificate /etc/ssl/gamelygame/cert.pem;
    ssl_certificate_key /etc/ssl/gamelygame/key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;

    resolver 127.0.0.11 valid=10s;
    set $upstream http://gamely-nginx:80;

    location / {
        proxy_pass $upstream;
        proxy_read_timeout 60s;
    }
}
